// sounds.js — resolver for the bundled sound-effect library (#sfx).
//
// The mp3s live in electron-app/sounds/<category>/<name>.mp3 and ship with the
// app (build.files globs "sounds/**/*"). manifest.json (generated by
// scripts/build-sounds-manifest.mjs) maps a sound id ("arcade/coin") to its
// file. The bot plays one via the play_sound MCP tool → local-server resolves
// the id to an absolute path here → reuses the existing play-audio path.
//
// __dirname resolves under both dev (electron-app/) and packaged builds (the
// asar app root), same as page-inject.js — so path.join(__dirname, 'sounds', …)
// is valid in both.

const fs = require('fs');
const path = require('path');

const SOUNDS_DIR = path.join(__dirname, 'sounds');

let _manifest = null;
function load() {
  if (_manifest) return _manifest;
  try {
    const raw = fs.readFileSync(path.join(SOUNDS_DIR, 'manifest.json'), 'utf-8');
    const parsed = JSON.parse(raw);
    const byId = new Map();
    for (const s of parsed.sounds || []) byId.set(s.id, s);
    _manifest = { ...parsed, byId };
  } catch (err) {
    console.error('[sounds] failed to load manifest:', err.message);
    _manifest = { sounds: [], byId: new Map() };
  }
  return _manifest;
}

// Resolve a sound id ("arcade/coin") to an absolute, existing file path, or null.
// Tolerant of a leading "sounds/" and of a missing/extra "/" — but the id must
// otherwise match a manifest entry (no silent fuzzy matching).
function resolvePath(id) {
  const m = load();
  const key = String(id || '').trim().replace(/^sounds\//, '');
  const entry = m.byId.get(key);
  if (!entry) return null;
  const abs = path.join(SOUNDS_DIR, entry.file);
  return fs.existsSync(abs) ? abs : null;
}

// All known sound ids (for error messages / validation).
function ids() {
  return (load().sounds || []).map((s) => s.id);
}

module.exports = { resolvePath, ids, SOUNDS_DIR };
